#!/usr/bin/env python3
# Lucas Green Book -- Copyright (c) 2026 Lucas Wu. "Lucas Green Book" is a trademark of Lucas Wu.
# Free for personal, non-commercial use. Licensed under PolyForm Noncommercial 1.0.0.
# https://github.com/lucasw9999/lucas-green-book
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
"""
Generate legal/05_DISCLAIMER_TEXT.md from the disclaimer the books ACTUALLY print.

Why generate it: the file said "verbatim" and was not. It described SIX distributed green books when
there are twelve; both quoted versions ended "(c) 2026 Lucas." while every real book prints
"(c) 2026 Lucas Wu - Lucas Green Book(TM). This book: free to share, not for sale - CC BY-NC-ND 4.0";
its own intro promised a coach-edition variant that the file never contained; and it predated the
USDA NAIP credit. A legal record whose whole value is being the exact printed words cannot be
maintained by hand -- if it drifts, the thing it is evidence FOR is no longer what it says.

Everything below is extracted from built books in courses/*/, never retyped.

Run:  python3 tools/gen_disclaimers.py            # writes legal/05_DISCLAIMER_TEXT.md
      python3 tools/gen_disclaimers.py --check    # exits 1 if stale (for CI / pre-merge)
"""
import glob
import html
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import distribution  # noqa: E402  (path set above)
OUT = os.path.join(ROOT, "legal", "05_DISCLAIMER_TEXT.md")

# The rationale section is genuine legal reasoning, not extracted text, so it is authored here and
# kept verbatim -- only the QUOTED disclaimer bodies are generated.
WHY = """## Why this text covers the risks
- **Independent / open-data provenance** -> copyright + trade-dress defense.
- **"no proprietary data/image/symbol/layout/trade dress used, copied, referenced or
  reverse-engineered" + "references no third-party brand"** -> forecloses copying/passing-off.
- **"not affiliated/endorsed/sponsored" + nominative course-name use + removal-on-request** ->
  trademark (nominative fair use) + defuses any course objection.
- **"built from remote public data, without entering any club"** -> no trespass / terms-of-entry.
- **"designed to conform ... not guaranteed ... confirm with Committee ... not responsible for
  penalty"** -> softens the Rule-4.3 claim and DQ liability.
- **"as-is, no warranty, not liable"** -> limits negligence/product-liability.
- **"not for sale"** -> negates the "commercial competitor" element in several theories.
- **CC BY-NC-ND 4.0 + "Lucas Green Book(TM)"** -> states the terms the book itself is offered under,
  so a redistributor has no excuse for selling it or shipping a modified version.
"""


def _text_of(abtxt_html):
    """The printed words of one <div class="abtxt"> block, tags and entities resolved."""
    t = re.sub(r"<[^>]+>", "", abtxt_html)
    t = html.unescape(t)
    return re.sub(r"\s+", " ", t).strip()


def _abtxt_blocks(path):
    h = open(path, encoding="utf-8").read()
    return [_text_of(m) for m in re.findall(r'<div class="abtxt">(.*?)</div>', h, re.S)]


def _wrap(t, width=96):
    out, line = [], "> "
    for w in t.split():
        if len(line) + len(w) + 1 > width:
            out.append(line.rstrip()); line = "> "
        line += w + " "
    out.append(line.rstrip())
    return "\n".join(out)


def _books(pattern):
    """Built books, excluding underscore-prefixed scratch/staging dirs.

    gen_provenance.py and the test suite both filter these; this tool did not, so a throwaway
    directory became a named distributed green book in a LEGAL record ("Variant A1 -- printed on 11
    book(s): _ccrit_noloc, bay-view-golf-club, ...") and --check told you to regenerate, i.e. to
    falsify the document."""
    for f in sorted(glob.glob(os.path.join(ROOT, "courses", "*", pattern))):
        if distribution.is_corpus_slug(os.path.basename(os.path.dirname(f))):
            yield f


def build():
    books = {}                                   # printed text -> [course slugs]
    for f in _books("greenbook.html"):
        slug = os.path.basename(os.path.dirname(f))
        for b in _abtxt_blocks(f):
            books.setdefault(b, []).append(slug)
    coach = {}
    for f in _books("greenbook_coach.html"):
        slug = os.path.basename(os.path.dirname(f))
        for b in _abtxt_blocks(f):
            coach.setdefault(b, []).append(slug)

    # Count BOTH editions. This counted pocket slugs only, so the file said "Covers 12 built books"
    # while section B below it documented three more -- and export_pdf --check reports 15. A record whose
    # own headline undercounts what it contains invites the reader to assume the rest is scoped too.
    _pocket = {s for v in books.values() for s in v}
    _coach = {s for v in coach.values() for s in v}
    n = len(_pocket) + len(_coach)
    L = ['# Disclaimer / "About & Legal" Text (verbatim)', "",
         "**GENERATED by `tools/gen_disclaimers.py` -- do not edit by hand.** Every quoted block below",
         "is extracted from a built book in `courses/`, so it cannot drift from what is printed.",
         "Re-run after any wording change; `--check` fails if this file is stale.", "",
         f"Covers **{n}** built books ({len(_pocket)} pocket, {len(_coach)} enlarged). Blocks differ per",
         "course where the data differs (a rebuilt",
         "course, a NAIP-traced green), so each variant is listed with the courses that print it.", ""]

    def section(letter, title, mapping):
        L.append(f"## {letter}. {title}")
        if not mapping:
            L.append("*(none built)*"); L.append(""); return
        for i, (txt, slugs) in enumerate(sorted(mapping.items(), key=lambda kv: -len(kv[1]))):
            L.append(f"### Variant {letter}{i + 1} -- printed on {len(slugs)} book(s): "
                     f"{', '.join(slugs)}")
            L.append(_wrap(txt)); L.append("")

    section("A", 'Pocket edition "About & legal"', books)
    section("B", 'Coach / ENLARGED edition "About & legal"', coach)
    L.append(WHY)
    return "\n".join(L)


def main():
    if not list(_books("greenbook.html")):
        print("no built books found -- build at least one course first "
              "(COURSE=<slug> python3 generate.py)")
        return 1
    if not list(_books("greenbook_coach.html")):
        # Writing a legal record that silently omits a DISTRIBUTED variant is the exact drift this
        # generator exists to stop, so refuse rather than emit an incomplete one.
        print("no coach edition built -- the enlarged book is distributed too, so its disclaimer\n"
              "  belongs in this record. Build one first:\n"
              "    COACH=1 COURSE=<slug> python3 generate.py")
        return 1
    new = build()
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if cur.strip() != new.strip():
            print(f"{os.path.relpath(OUT, ROOT)} is STALE -- run: python3 tools/gen_disclaimers.py")
            return 1
        print(f"{os.path.relpath(OUT, ROOT)} is up to date")
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(new + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
